-- I got this list from production
use `Afton`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `Andes`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `AntelopeButte`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `BigHorn`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `BlackjackMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;

use `Brighton`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;


use `BuenaVista`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `CoffeeMill`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `DetroitMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `DevilsHead`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `ElmCreek`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `GrandTarghee`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `GreatDivide`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `HermonMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `Hesperus`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `HiddenValley`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `HylandHills`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `IFNordic`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `IndianHeadMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `KellyCanyon`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `LeeCanyon`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `LonesomePine`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `MagicMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `MountKato`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `MountPleasant`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `NorwayMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `PaidSnowCreek`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `PaulBunyan`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `PebbleCreek`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `PineCreek`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `PineMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `Plattekill`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `Pomerelle`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `RMSP`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;


use `Sample`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;


use `SnowCreek`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `SnowKing`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `Snowbowl`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `SoldierHollow`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `SoldierMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `WelchVillage`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `WhitePine`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `WildMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `Willamette`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `psiaMagicMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
use `psiaPineMountain`;
ALTER TABLE `roster` ADD `newPassword` VARCHAR(128) NOT NULL AFTER `comments`;
